# Generated by Django 4.2.5 on 2023-09-13 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Videogame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acronym", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("modified_at", models.DateTimeField()),
                ("slug", models.SlugField(unique=True)),
                (
                    "current_videogame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EsportHub.videogame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("modified_at", models.DateTimeField()),
                ("name", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=2)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="EsportHub.team",
                    ),
                ),
            ],
        ),
    ]
