# Generated by Django 4.2.5 on 2023-09-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EsportHub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogame",
            name="slug",
            field=models.SlugField(),
        ),
    ]
