# Generated by Django 4.2.5 on 2023-09-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EsportHub", "0002_alter_videogame_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(),
        ),
    ]
