# Generated by Django 4.2.5 on 2023-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EsportHub", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
    ]
